/**:
  ros__parameters:
    # Low resolution video mode (480p 4:3)
    lowres_frame_width: 640
    lowres_frame_height: 480
    lowres_bitrate: 1500

    # High resolution video mode (720p 4:3)
    highres_frame_width: 960
    highres_frame_height: 720
    highres_bitrate: 2500

    # Maximum number of frames streamed per second
    frames_per_second: 25

    pipeline: >
      appsrc name=appsrc is-live=true block=true format=time
      caps=video/x-raw,format=RGB,width={width},height={height},framerate={fps}/1 !
      videoconvert !
      x264enc tune=zerolatency bitrate={bitrate} speed-preset=ultrafast intra-refresh=true
      sliced-threads=true byte-stream=true vbv-buf-capacity={bitrate_div_fps} bframes=0
      b-adapt=0 ref=1 key-int-max={fps} !
      video/x-h264, profile=baseline !
      rtph264pay pt=96 !
      udpsink host=127.0.0.1 port={port}
